
# Spring Application Name
spring.application.name=Web Services Platform

# Server Port Configuration
server.port=9090

# Spring DataSource Configuration

spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://ep-summer-shadow-ad01bhmh-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_8ANCzkv6OETW&sslmode=require&channelBinding=require



# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.paxtech.utime.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days = 7

#Flyway Configuration
spring.flyway.enabled=false

# application.properties
logging.file.name=/home/LogFiles/Application/app.log
logging.level.root=INFO
